### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by Slimfit** [climatepatch/formation#6]
There are a lot of ideas coming in covering a lot of different problems and tech. I think an important first conversation to have is how can we provide a platform that allows us to work in parallel on separate projects, but have them all add value to each other and the same user base. 

I envision this as an api that we could consume from any type of client. With this, a more controlled core team develops the api and database while many other teams spin up their own projects, to consume the data for their mobile apps and IoT. 

An example of this with the ideas we have on the board so far:
1. We launch a website with a simple blog and [collection of resources](https://github.com/Slimfit/climatepatch/issues/1#issuecomment-259966167). Users find it and want to stay in touch, so the register. 
2. Next release we [deploy a tool](https://github.com/Slimfit/climatepatch/issues/3) to the site that allows the user to simulate how humans can impact key global metrics, and how changes to those metrics affect where they live. The tool requires them to manually provide their estimates for their own CO2 emission.
3. We release a [device ](https://github.com/Slimfit/climatepatch/issues/1#issuecomment-259902143)(or tap into existing products api) that automatically tracks energy usage in their home. Use this to more precisely determine the users impact in real time. Allow them to receive periodic updates or warnings and tips on how to limit their consumption.

These are 3 manageable projects that could potentially be developed in parallel using different programming languages by different programmers, but all improve one another.

**Comment by cqcwillard** [comment]
I'm definitely in favor of an API.  Lately I've been leaning on JS stacks to do my backend API development.  Sails has proven to be a solid JS API library for me and my team.

I'm more in favor of using frameworks that provide out of the box realtime communication.  Sails has a neat feature where they provide socket based access to your existing API structure.

http://sailsjs.org/

**Comment by cqcwillard** [comment]
I think the simplest thing we can do is start a GitBook for the curated list of studies, and a static blog to start getting the project and ideas out there.

**Comment by indigocarmen** [comment]
I am not too familiar with Gitbooks, I'll have to do a bit of research. I wonder if we could use a web scraper on Google Scholar to pull all relevant studies/evidence that it has?

**Comment by birdyboy18** [comment]
Hey All,

I caught wind of this thing on reddit earlier. I'm also interested in helping out where I can. I'm typically a full stack / Wordpress developer. But love to write APIs in node.

@cqcwillard I've not used sails so I'd be intrigued. But I'm also adverse slightly to all frameworks because of how much work they do and being locked into their way of doing things, but feel free to convince me otherwise.

On the topic of realtime I wanted to point you in the direction of rethinkdb - https://www.rethinkdb.com/ I've used it and it handles realtime built in by subscribing to changefeeds. It's really nice. Unfortunately it got somewhat discontinued but I'm certain it's going to be released back to the community for other people to take over.

I look forward to hearing your responses!

**Comment by Slimfit** [comment]
Closing this. Architecture will depend on the solution.
